### ISSUE TITLE
window.safeMutableDataEntries.forEach , v 0.4.3

### ISSUE THREAD

**Issue by wrnice** [maidsafe/beaker-plugin-safe-app#117]
When using `window.safeMutableDataEntries.forEach` ,

until browser 0.7 , I used to be able to read the returned keys as strings.

Now, with the 0.8 browser  I get an object in the form of : 
Object {0: 95, 1: 109, 2: 101, 3: 116, 4: 97, 5: 100, 6: 97, 7: 116, 8: 97, _refs: Array(1)} 

I see that this one translates  into :" _metadata"  ,   "_"

Is window.safeMutableDataEntries.forEach supposed to return a key for the mutable metadata ? I don't think it was the case before.

How do you access the key name now ?  the doc  ( 0.4.3 ) says : k.toString()  ,  but this just returns "[object Object]"

**Comment by happybeing** [comment]
I have the same issue. App that works with SB 0.7.0 now fails with SB 0.8.0 because inside a `forEach()` the key is an object rather than a string rather than previously. The code, and the [documentation](http://docs.maidsafe.net/beaker-plugin-safe-app/#windowsafemutabledataentriesforeach) use `k.toString()` but this no longer works.

**Comment by wrnice** [comment]
this is a duplicate of : https://github.com/maidsafe/beaker-plugin-safe-app/issues/114
